# Classification on Disaster Tweets

## Context

The file contains over 11,000 tweets associated with disaster keywords like “crash”, “quarantine”, and “bush fires” as well as the location and keyword itself. The data structure was inherited from Disasters on social media

The tweets were collected on Jan 14th, 2020.

### Some of the topics people were tweeting:

The eruption of Taal Volcano in Batangas, Philippines
Coronavirus
Bushfires in Australia
Iran downing of the airplane flight PS752
Disclaimer: The dataset contains text that may be considered profane, vulgar, or offensive.

In [1]:
#Kaggle Link :https://www.kaggle.com/vstepanenko/disaster-tweets

In [2]:
#importing libraries

In [3]:
import numpy as np
import pandas as pd
import math
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
#Rest of the libarires will be imported wehere ever necessary

In [4]:
#Reading the dataset

In [5]:
df=pd.read_csv('D:\\M. Tech in Data Science & Machine Learning\\Natural language processing (NLP)\\Sem Preparation\\Disaster Tweets\\tweets.csv')
df.head()#reading first 5 observations

id keyword        location  \
0   0  ablaze             NaN   
1   1  ablaze             NaN   
2   2  ablaze   New York City   
3   3  ablaze  Morgantown, WV   
4   4  ablaze             NaN   

                                                text  target  
0  Communal violence in Bhainsa, Telangana. "Ston...       1  
1  Telangana: Section 144 has been imposed in Bha...       1  
2  Arsonist sets cars ablaze at dealership https:...       1  
3  Arsonist sets cars ablaze at dealership https:...       1  
4  "Lord Jesus, your love brings freedom and pard...       0

In [6]:
df.tail()#reading last 5 observations

id  keyword                 location  \
11365  11365  wrecked  Blue State in a red sea   
11366  11366  wrecked               arohaonces   
11367  11367  wrecked                       🇵🇭   
11368  11368  wrecked           auroraborealis   
11369  11369  wrecked                      NaN   

                                                    text  target  
11365  Media should have warned us well in advance. T...       0  
11366  i feel directly attacked 💀 i consider moonbin ...       0  
11367  i feel directly attacked 💀 i consider moonbin ...       0  
11368  ok who remember "outcast" nd the "dora" au?? T...       0  
11369     Jake Corway wrecked while running 14th at IRP.       1

In [7]:
df.shape #11370 records and 5 features in total including target variable

(11370, 5)

In [8]:
df.info()#summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11370 entries, 0 to 11369
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        11370 non-null  int64 
 1   keyword   11370 non-null  object
 2   location  7952 non-null   object
 3   text      11370 non-null  object
 4   target    11370 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 444.3+ KB


In [9]:
#inferences:

#2 features are numeric and 3 features are categorical

In [10]:
df1=df.iloc[:,3:]#only selecting the siginfact variables for our analysis
df1.head()

text  target
0  Communal violence in Bhainsa, Telangana. "Ston...       1
1  Telangana: Section 144 has been imposed in Bha...       1
2  Arsonist sets cars ablaze at dealership https:...       1
3  Arsonist sets cars ablaze at dealership https:...       1
4  "Lord Jesus, your love brings freedom and pard...       0

In [11]:
#cleaning of the Data

In [12]:
#1. Lowercase and Replace

In [13]:
##remove everything other than ^a-z\s
#^a-z:lowe case alphabets
#\s:space

In [14]:
df1['text_clean']=df1['text'].str.lower().str.replace('[^a-z\s]','')
df1.head()

text  target  \
0  Communal violence in Bhainsa, Telangana. "Ston...       1   
1  Telangana: Section 144 has been imposed in Bha...       1   
2  Arsonist sets cars ablaze at dealership https:...       1   
3  Arsonist sets cars ablaze at dealership https:...       1   
4  "Lord Jesus, your love brings freedom and pard...       0   

                                          text_clean  
0  communal violence in bhainsa telangana stones ...  
1  telangana section  has been imposed in bhainsa...  
2  arsonist sets cars ablaze at dealership httpst...  
3  arsonist sets cars ablaze at dealership httpst...  
4  lord jesus your love brings freedom and pardon...

In [15]:
#2. Tokenize

In [16]:
#In Python tokenization basically refers to splitting up a larger body of text into smaller lines, 
#words or even creating words for a non-English language

In [17]:
df1['text_clean']=df1['text_clean'].str.split(' ')
df1.head()

text  target  \
0  Communal violence in Bhainsa, Telangana. "Ston...       1   
1  Telangana: Section 144 has been imposed in Bha...       1   
2  Arsonist sets cars ablaze at dealership https:...       1   
3  Arsonist sets cars ablaze at dealership https:...       1   
4  "Lord Jesus, your love brings freedom and pard...       0   

                                          text_clean  
0  [communal, violence, in, bhainsa, telangana, s...  
1  [telangana, section, , has, been, imposed, in,...  
2  [arsonist, sets, cars, ablaze, at, dealership,...  
3  [arsonist, sets, cars, ablaze, at, dealership,...  
4  [lord, jesus, your, love, brings, freedom, and...

In [18]:
#3. Removing Stopwords

In [19]:
import nltk

In [20]:
#Stopwords are the English words which does not add much meaning to a sentence.

In [21]:
common_Stopwords=nltk.corpus.stopwords.words('english')
print(common_Stopwords)#dowladed the common stopwords from nltk library

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [22]:
len(common_Stopwords)

179

In [23]:
common_Stopwords.remove('no')
common_Stopwords.remove('nor')
common_Stopwords.remove('not')

In [24]:
len(common_Stopwords)#some words have been removed

176

In [25]:
def drop_stopwords(text):
    return [word for word in text if word not in common_Stopwords]

In [26]:
df1['text_clean']=df1['text_clean'].apply(drop_stopwords)
df1.head()

text  target  \
0  Communal violence in Bhainsa, Telangana. "Ston...       1   
1  Telangana: Section 144 has been imposed in Bha...       1   
2  Arsonist sets cars ablaze at dealership https:...       1   
3  Arsonist sets cars ablaze at dealership https:...       1   
4  "Lord Jesus, your love brings freedom and pard...       0   

                                          text_clean  
0  [communal, violence, bhainsa, telangana, stone...  
1  [telangana, section, , imposed, bhainsa, janua...  
2  [arsonist, sets, cars, ablaze, dealership, htt...  
3  [arsonist, sets, cars, ablaze, dealership, htt...  
4  [lord, jesus, love, brings, freedom, pardon, f...

In [27]:
#4. Lemmatization

In [28]:
from nltk.stem.wordnet import WordNetLemmatizer
Lemmatization=WordNetLemmatizer()

In [29]:
def lemmatization(text):
    return [Lemmatization.lemmatize(word) for word in text]

In [30]:
df1['text_clean']=df1['text_clean'].apply(lemmatization)
df1.head()

text  target  \
0  Communal violence in Bhainsa, Telangana. "Ston...       1   
1  Telangana: Section 144 has been imposed in Bha...       1   
2  Arsonist sets cars ablaze at dealership https:...       1   
3  Arsonist sets cars ablaze at dealership https:...       1   
4  "Lord Jesus, your love brings freedom and pard...       0   

                                          text_clean  
0  [communal, violence, bhainsa, telangana, stone...  
1  [telangana, section, , imposed, bhainsa, janua...  
2  [arsonist, set, car, ablaze, dealership, https...  
3  [arsonist, set, car, ablaze, dealership, https...  
4  [lord, jesus, love, brings, freedom, pardon, f...

In [31]:
#5. Clean the text

In [32]:
df1['text_clean']=df1['text_clean'].apply(lambda x: ' '.join(x))
df1.head()

text  target  \
0  Communal violence in Bhainsa, Telangana. "Ston...       1   
1  Telangana: Section 144 has been imposed in Bha...       1   
2  Arsonist sets cars ablaze at dealership https:...       1   
3  Arsonist sets cars ablaze at dealership https:...       1   
4  "Lord Jesus, your love brings freedom and pard...       0   

                                          text_clean  
0  communal violence bhainsa telangana stone pelt...  
1  telangana section  imposed bhainsa january   c...  
2  arsonist set car ablaze dealership httpstcogoq...  
3  arsonist set car ablaze dealership httpstcogln...  
4  lord jesus love brings freedom pardon fill hol...

In [33]:
#checking the target variable

In [34]:
df1['target'].value_counts()

0    9256
1    2114
Name: target, dtype: int64

In [35]:
##Vectorizing

In [36]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [37]:
Tfidf=TfidfVectorizer(max_features=2500)

In [38]:
X1=Tfidf.fit_transform(df1['text_clean'])#independent Variable

In [39]:
Y1=df1['target']#target variable

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [42]:
x_tain,x_test,y_train,y_test=train_test_split(X1, Y1, test_size=0.15, random_state=2)

In [43]:
#Modelling

In [44]:
#1. KNeighborsClassifier

In [45]:
from sklearn.neighbors import KNeighborsClassifier

In [46]:
knc=KNeighborsClassifier()
K_Neighbors_Classifier=knc.fit(x_tain,y_train)

In [47]:
knc_pred=K_Neighbors_Classifier.predict(x_test)

In [48]:
print(classification_report(knc_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.85      0.92      1640
           1       0.20      0.91      0.33        66

    accuracy                           0.85      1706
   macro avg       0.60      0.88      0.62      1706
weighted avg       0.96      0.85      0.90      1706



In [49]:
confusion_matrix(knc_pred,y_test)

array([[1398,  242],
       [   6,   60]], dtype=int64)

In [50]:
accuracy_score(knc_pred,y_test)*100

85.4630715123095

In [51]:
##Inference:

#Accuracy of the model is 85.63

#Precison of the model is high amlost 0.62

#TPR(true positive rate) ie, Recall is also high 0.84

In [52]:
#2. Support Vector machine

In [53]:
from sklearn.svm import SVC

In [54]:
svc=SVC()
Support_Vector_machine=svc.fit(x_tain,y_train)

In [55]:
svm_pred=Support_Vector_machine.predict(x_test)

In [56]:
print(classification_report(svm_pred,y_test))

              precision    recall  f1-score   support

           0       0.99      0.90      0.94      1544
           1       0.47      0.88      0.61       162

    accuracy                           0.89      1706
   macro avg       0.73      0.89      0.78      1706
weighted avg       0.94      0.89      0.91      1706



In [57]:
confusion_matrix(svm_pred,y_test)

array([[1384,  160],
       [  20,  142]], dtype=int64)

In [58]:
accuracy_score(svm_pred,y_test)*100

89.44900351699883

In [59]:
##Inference:

#Accuracy of the model is 89.44

#Precison of the model is high amlost 0.72

#TPR(true positive rate) ie, Recall is also high 0.89

In [60]:
#3. Decision Tree Classifier

In [61]:
from sklearn.tree import DecisionTreeClassifier

In [62]:
dtc=DecisionTreeClassifier()
DecisionTree_Classifier=dtc.fit(x_tain,y_train)

In [63]:
dtc_pred=DecisionTree_Classifier.predict(x_test)

In [64]:
print(classification_report(dtc_pred,y_test))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92      1425
           1       0.59      0.64      0.61       281

    accuracy                           0.87      1706
   macro avg       0.76      0.78      0.77      1706
weighted avg       0.87      0.87      0.87      1706



In [65]:
confusion_matrix(dtc_pred,y_test)

array([[1302,  123],
       [ 102,  179]], dtype=int64)

In [66]:
accuracy_score(dtc_pred,y_test)*100

86.81125439624854

In [67]:
##Inference:

#Accuracy of the model is 86.98

#Precison of the model is high amlost 0.75

#TPR(true positive rate) ie, Recall is also high 0.78

In [68]:
#4. Random Forest Classifier (bagging)

In [69]:
from sklearn.ensemble import RandomForestClassifier

In [70]:
rfc=RandomForestClassifier()
Random_Forest_Classifier=rfc.fit(x_tain,y_train)

In [71]:
rfc_pred=Random_Forest_Classifier.predict(x_test)

In [72]:
print(classification_report(rfc_pred,y_test))

              precision    recall  f1-score   support

           0       0.97      0.90      0.93      1500
           1       0.53      0.77      0.63       206

    accuracy                           0.89      1706
   macro avg       0.75      0.84      0.78      1706
weighted avg       0.91      0.89      0.90      1706



In [73]:
confusion_matrix(rfc_pred,y_test)

array([[1357,  143],
       [  47,  159]], dtype=int64)

In [74]:
accuracy_score(rfc_pred,y_test)*100

88.862837045721

In [75]:
##Inference:

#Accuracy of the model is 89.39

#Precison of the model is high amlost 0.76

#TPR(true positive rate) ie, Recall is also high 0.84

In [76]:
#5. AdaBoostClassifier (Boosting)

In [77]:
from sklearn.ensemble import AdaBoostClassifier

In [78]:
ada=AdaBoostClassifier()
Ada_Boost_Classifier=ada.fit(x_tain,y_train)

In [79]:
ada_pred=Ada_Boost_Classifier.predict(x_test)

In [80]:
print(classification_report(ada_pred,y_test))

              precision    recall  f1-score   support

           0       0.96      0.87      0.91      1549
           1       0.34      0.65      0.44       157

    accuracy                           0.85      1706
   macro avg       0.65      0.76      0.68      1706
weighted avg       0.90      0.85      0.87      1706



In [81]:
confusion_matrix(ada_pred,y_test)

array([[1349,  200],
       [  55,  102]], dtype=int64)

In [82]:
accuracy_score(ada_pred,y_test)*100

85.052754982415

In [83]:
##Inference:

#Accuracy of the model is 85.52

#Precison of the model is high amlost 0.66

#TPR(true positive rate) ie, Recall is also high 0.78

In [84]:
#6. GradientBoostingClassifier (Boosting)

In [85]:
from sklearn.ensemble import GradientBoostingClassifier

In [86]:
gbc=GradientBoostingClassifier()
Gradient_Boosting_Classifier=gbc.fit(x_tain,y_train)

In [87]:
gbc_pred=Gradient_Boosting_Classifier.predict(x_test)

In [88]:
print(classification_report(gbc_pred,y_test))

              precision    recall  f1-score   support

           0       0.99      0.85      0.92      1629
           1       0.22      0.84      0.34        77

    accuracy                           0.85      1706
   macro avg       0.60      0.85      0.63      1706
weighted avg       0.96      0.85      0.89      1706



In [89]:
confusion_matrix(gbc_pred,y_test)

array([[1392,  237],
       [  12,   65]], dtype=int64)

In [90]:
accuracy_score(gbc_pred,y_test)*100

85.4044548651817

In [91]:
##Inference:

#Accuracy of the model is 85.11

#Precison of the model is high amlost 0.60

#TPR(true positive rate) ie, Recall is also high 0.84

In [92]:
#7. XGBClassifier:xgboost classifier (Boosting)

In [93]:
#!pip install xgboost

In [94]:
from xgboost import XGBClassifier

In [95]:
xgb=XGBClassifier()
XGB_Classifier=xgb.fit(x_tain,y_train)

[19:26:31] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [96]:
xgb_pred=XGB_Classifier.predict(x_test)

In [97]:
print(classification_report(xgb_pred,y_test))

              precision    recall  f1-score   support

           0       0.98      0.88      0.93      1561
           1       0.39      0.81      0.52       145

    accuracy                           0.88      1706
   macro avg       0.68      0.84      0.73      1706
weighted avg       0.93      0.88      0.89      1706



In [98]:
confusion_matrix(xgb_pred,y_test)

array([[1376,  185],
       [  28,  117]], dtype=int64)

In [99]:
accuracy_score(xgb_pred,y_test)*100

87.51465416178195

In [100]:
#LSTM

In [101]:
#Long Short-Term Memory (LSTM) networks are a type of recurrent neural network capable of learning order dependence in sequence prediction problems. 

In [102]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [103]:
df1.head()

text  target  \
0  Communal violence in Bhainsa, Telangana. "Ston...       1   
1  Telangana: Section 144 has been imposed in Bha...       1   
2  Arsonist sets cars ablaze at dealership https:...       1   
3  Arsonist sets cars ablaze at dealership https:...       1   
4  "Lord Jesus, your love brings freedom and pard...       0   

                                          text_clean  
0  communal violence bhainsa telangana stone pelt...  
1  telangana section  imposed bhainsa january   c...  
2  arsonist set car ablaze dealership httpstcogoq...  
3  arsonist set car ablaze dealership httpstcogln...  
4  lord jesus love brings freedom pardon fill hol...

In [104]:
vocabSize=2500
tokenizer = Tokenizer(num_words=vocabSize,split=' ')#split on space
tokenizer.fit_on_texts(df1['text_clean'].values)

#fit_on_texts :Updates internal vocabulary based on a list of texts. 
    #This method creates the vocabulary index based on word frequency. 
    #So if you give it something like, "The cat sat on the mat."
    #It will create a dictionary s.t. word_index["the"] = 1; word_index["cat"] = 2 it is word -> index dictionary so every word gets a unique integer value. 
    #0 is reserved for padding. So lower integer means more frequent word (often the first few are stop words because they appear a lot).

In [105]:
vocab_size=tokenizer.word_index#word_index
vocab_size

{'not': 1,
 'amp': 2,
 'like': 3,
 'people': 4,
 'fire': 5,
 'u': 6,
 'im': 7,
 'no': 8,
 'one': 9,
 'get': 10,
 'year': 11,
 'dont': 12,
 'time': 13,
 'need': 14,
 'day': 15,
 'new': 16,
 'know': 17,
 'would': 18,
 'say': 19,
 'iran': 20,
 'first': 21,
 'see': 22,
 'think': 23,
 'today': 24,
 'storm': 25,
 'go': 26,
 'death': 27,
 'want': 28,
 'still': 29,
 'trump': 30,
 'emergency': 31,
 'back': 32,
 'man': 33,
 'world': 34,
 'two': 35,
 'let': 36,
 'australia': 37,
 'body': 38,
 'many': 39,
 'news': 40,
 'make': 41,
 'cant': 42,
 'attack': 43,
 'got': 44,
 'please': 45,
 'help': 46,
 'good': 47,
 'th': 48,
 'right': 49,
 'really': 50,
 'also': 51,
 'last': 52,
 'could': 53,
 'said': 54,
 'much': 55,
 'home': 56,
 'thats': 57,
 'come': 58,
 'love': 59,
 'nuclear': 60,
 'volcano': 61,
 'woman': 62,
 'take': 63,
 'killed': 64,
 'even': 65,
 'look': 66,
 'never': 67,
 'life': 68,
 'bomb': 69,
 'police': 70,
 'house': 71,
 'going': 72,
 'service': 73,
 'state': 74,
 'taal': 75,
 'thing':

In [106]:
len(vocab_size)

25194

In [107]:
X2 = tokenizer.texts_to_sequences(df1['text_clean'].values)
#texts_to_sequences: Transforms each text in texts to a sequence of integers. 
    #So it basically takes each word in the text and replaces it with its corresponding integer value from the word_index dictionary. 
    #Nothing more, nothing less, certainly no magic involved.

In [108]:
X2

[[678, 1478, 1550, 983, 335, 71, 71, 460, 158, 848],
 [1550, 2073, 1478, 215, 2258, 1752, 35, 416, 215, 1308],
 [1137, 158, 188, 848],
 [1137, 158, 188, 848],
 [1138, 786, 59, 1753, 1309, 1479, 158, 106, 848, 565],
 [125, 754, 336, 18, 735, 2259, 1086, 189, 18, 848, 18, 111, 1251, 348],
 [529, 71, 158, 848, 1139, 1901, 368, 639, 755, 2499],
 [1551, 954, 1139, 158, 848, 52, 132, 1551, 545, 471, 70, 107],
 [320, 583, 708, 427, 158, 921, 848, 736, 659, 100],
 [955, 787, 8, 849, 984, 848, 76, 1754, 1754],
 [756, 985, 355, 2499, 165, 71, 165, 640],
 [1086, 189, 321, 660, 986, 244, 709],
 [1651, 158, 116, 954, 369, 1252, 1902, 116, 848, 116, 954],
 [757, 678, 2, 737, 639, 954],
 [158, 301, 370, 848, 33],
 [756, 985, 355, 2499, 165, 71, 165],
 [8, 24, 369, 2074, 29, 848],
 [158, 106, 848, 267, 1755, 146],
 [848, 47, 986],
 [2260, 158, 71, 848, 35, 392, 393, 56, 1756, 382],
 [2499, 417, 1139, 1757, 848, 710],
 [5, 848, 679, 58, 79, 58, 302],
 [1903, 150, 1903, 226],
 [884, 5, 1, 711, 1, 158, 8

In [109]:
X2 = pad_sequences(X2)#pad_sequences is used to ensure that all sequences in a list have the same length.

In [110]:
X2.shape#overall shape of x

(11370, 21)

In [111]:
#More explanation of .fit_on_texts and .texts_to_sequences on belwo link

#https://stackoverflow.com/questions/51956000/what-does-keras-tokenizer-method-exactly-do

In [112]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, SpatialDropout1D

In [113]:
embed_dim = 128
lstm_out = 196

model = Sequential()
model.add(Embedding(vocabSize, embed_dim,input_length = X2.shape[1]))
#vocabSize:input_dim (Integer. Size of the vocabulary, i.e. maximum integer index + 1.)
#embed_dim:output_dim (Integer. Dimension of the dense embedding.)
#input_length: Length of input sequences
model.add(SpatialDropout1D(0.4))#explained below
model.add(LSTM(lstm_out, dropout=0.2, recurrent_dropout=0.2))
#lstm_out : Positive integer, dimensionality of the output space.
model.add(Dense(2,activation='sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer='adam',metrics = ['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 21, 128)           320000    
_________________________________________________________________
spatial_dropout1d (SpatialDr (None, 21, 128)           0         
_________________________________________________________________
lstm (LSTM)                  (None, 196)               254800    
_________________________________________________________________
dense (Dense)                (None, 2)                 394       
Total params: 575,194
Trainable params: 575,194
Non-trainable params: 0
_________________________________________________________________
None


In [114]:
#What is SpatialDropout1D?

In [115]:
#Dropout(): Let's define 2D input: [[1, 1, 1], [2, 2, 2]]. 
            #Dropout will consider every element independently, and may result in something like [[1, 0, 1], [0, 2, 2]]
    
#SpatialDropout1D(): In this case result will look like [[1, 0, 1], [2, 0, 2]]. 
                    #Notice that 2nd element was zeroed along all channels.

In [116]:
from sklearn.model_selection import train_test_split

Y2 = pd.get_dummies(df1['target']).values
X_train2, X_test2, Y_train2, Y_test2 = train_test_split(X2,Y2, test_size = 0.15, random_state = 42)
print(X_train2.shape,Y_train2.shape)
print(X_test2.shape,Y_test2.shape)

(9664, 21) (9664, 2)
(1706, 21) (1706, 2)


In [117]:
batch_size = 40
model.fit(X_train2, Y_train2, epochs = 10, batch_size=batch_size, verbose = 1)

Epoch 1/10
242/242 [==============================] - 36s 115ms/step - loss: 0.3842 - accuracy: 0.8431
Epoch 2/10
242/242 [==============================] - 27s 112ms/step - loss: 0.2536 - accuracy: 0.9036
Epoch 3/10
242/242 [==============================] - 30s 124ms/step - loss: 0.2166 - accuracy: 0.9173
Epoch 4/10
242/242 [==============================] - 30s 123ms/step - loss: 0.1870 - accuracy: 0.9280
Epoch 5/10
242/242 [==============================] - 31s 127ms/step - loss: 0.1593 - accuracy: 0.9396
Epoch 6/10
242/242 [==============================] - 30s 125ms/step - loss: 0.1370 - accuracy: 0.9487
Epoch 7/10
242/242 [==============================] - 30s 125ms/step - loss: 0.1139 - accuracy: 0.9578
Epoch 8/10
242/242 [==============================] - 33s 136ms/step - loss: 0.1005 - accuracy: 0.9623
Epoch 9/10
242/242 [==============================] - 34s 140ms/step - loss: 0.0883 - accuracy: 0.9674
Epoch 10/10
242/242 [==============================] - 30s 126ms/step - l

In [118]:
score,acc = model.evaluate(X_test2, Y_test2, verbose = 1, batch_size = batch_size)
print("score: %.2f" % (score))
print("accuracy: %.2f" % (acc))

43/43 [==============================] - 2s 25ms/step - loss: 0.4974 - accuracy: 0.8681 0s - loss: 0.464
score: 0.50
accuracy: 0.87


In [119]:
#---------------------------------------------------END--------------------------------------------------------------------------------#